ALTER TABLE "conversations" ADD COLUMN "scan_id" integer;--> statement-breakpoint
ALTER TABLE "conversations" ADD CONSTRAINT "conversations_scan_id_scans_id_fk" FOREIGN KEY ("scan_id") REFERENCES "public"."scans"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "scans" DROP COLUMN "risk_forecast";--> statement-breakpoint
ALTER TABLE "scans" DROP COLUMN "revenue_intelligence";--> statement-breakpoint
ALTER TABLE "scans" DROP COLUMN "compliance_results";--> statement-breakpoint
ALTER TABLE "scans" DROP COLUMN "proof_evidence";--> statement-breakpoint
ALTER TABLE "scans" DROP COLUMN "regression_diff";--> statement-breakpoint
ALTER TABLE "scans" DROP COLUMN "benchmark_percentile";--> statement-breakpoint
ALTER TABLE "scans" DROP COLUMN "launch_dna";--> statement-breakpoint
ALTER TABLE "scans" DROP COLUMN "cofounder_narrative";--> statement-breakpoint
ALTER TABLE "scans" DROP COLUMN "shadow_api_findings";--> statement-breakpoint
ALTER TABLE "scans" DROP COLUMN "launch_replay_steps";--> statement-breakpoint
ALTER TABLE "scans" DROP COLUMN "secret_scan_results";--> statement-breakpoint
ALTER TABLE "scans" DROP COLUMN "package_vulns";--> statement-breakpoint
ALTER TABLE "scans" DROP COLUMN "cleanup_report";--> statement-breakpoint
ALTER TABLE "scans" DROP COLUMN "cleanup_findings";--> statement-breakpoint
ALTER TABLE "scans" DROP COLUMN "digital_twin";--> statement-breakpoint
ALTER TABLE "scans" DROP COLUMN "predictive_intel";--> statement-breakpoint
ALTER TABLE "scans" DROP COLUMN "root_cause";--> statement-breakpoint
ALTER TABLE "scans" DROP COLUMN "launch_impact";--> statement-breakpoint
ALTER TABLE "scans" DROP COLUMN "product_hunt_score";--> statement-breakpoint
ALTER TABLE "scans" DROP COLUMN "knowledge_graph";--> statement-breakpoint
ALTER TABLE "scans" DROP COLUMN "sandbox_meta";--> statement-breakpoint
ALTER TABLE "scans" DROP COLUMN "sbom_data";--> statement-breakpoint
ALTER TABLE "scans" DROP COLUMN "genome_fingerprint";--> statement-breakpoint
ALTER TABLE "scans" DROP COLUMN "causal_inference";--> statement-breakpoint
ALTER TABLE "scans" DROP COLUMN "quantitative_risk";--> statement-breakpoint
ALTER TABLE "scans" DROP COLUMN "genetic_drift";--> statement-breakpoint
ALTER TABLE "scans" DROP COLUMN "agent_debate_results";--> statement-breakpoint
ALTER TABLE "scans" DROP COLUMN "shadow_traffic_insight";--> statement-breakpoint
ALTER TABLE "scans" DROP COLUMN "developer_twin_profile";--> statement-breakpoint
ALTER TABLE "scans" DROP COLUMN "topological_analysis";--> statement-breakpoint
ALTER TABLE "scans" DROP COLUMN "quantum_verification";--> statement-breakpoint
ALTER TABLE "scans" DROP COLUMN "predictive_smt";--> statement-breakpoint
ALTER TABLE "scans" DROP COLUMN "zero_trust_enclave";--> statement-breakpoint
ALTER TABLE "scans" DROP COLUMN "market_readiness_tracker";--> statement-breakpoint
ALTER TABLE "scans" DROP COLUMN "ux_cognitive_flow";--> statement-breakpoint
ALTER TABLE "scans" DROP COLUMN "green_light_verdict";--> statement-breakpoint
ALTER TABLE "scans" DROP COLUMN "babel_engine";--> statement-breakpoint
ALTER TABLE "scans" DROP COLUMN "multi_verse_dse";--> statement-breakpoint
ALTER TABLE "scans" DROP COLUMN "zk_snark_proof";--> statement-breakpoint
ALTER TABLE "scans" DROP COLUMN "big_o_profiler";--> statement-breakpoint
ALTER TABLE "scans" DROP COLUMN "fhe_analyzer";--> statement-breakpoint
ALTER TABLE "scans" DROP COLUMN "neuromorphic_drift";--> statement-breakpoint
ALTER TABLE "scans" DROP COLUMN "tensor_payload_signature";--> statement-breakpoint
ALTER TABLE "scans" DROP COLUMN "engine_scorecards";--> statement-breakpoint
ALTER TABLE "scans" DROP COLUMN "auth_testing_payload";--> statement-breakpoint
ALTER TABLE "scans" DROP COLUMN "url_audit_score";--> statement-breakpoint
ALTER TABLE "scans" DROP COLUMN "post_quantum_readiness";--> statement-breakpoint
ALTER TABLE "scans" DROP COLUMN "dna_storage_compiler";--> statement-breakpoint
ALTER TABLE "scans" DROP COLUMN "bft_consensus_graph";--> statement-breakpoint
ALTER TABLE "scans" DROP COLUMN "kardashev_latency";--> statement-breakpoint
ALTER TABLE "scans" DROP COLUMN "agi_alignment";--> statement-breakpoint
ALTER TABLE "scans" DROP COLUMN "thermodynamic_entropy";--> statement-breakpoint
ALTER TABLE "scans" DROP COLUMN "vibe_taint";--> statement-breakpoint
ALTER TABLE "scans" DROP COLUMN "sym_cost";--> statement-breakpoint
ALTER TABLE "scans" DROP COLUMN "reg_graph";--> statement-breakpoint
ALTER TABLE "scans" DROP COLUMN "fail_safe";--> statement-breakpoint
ALTER TABLE "scans" DROP COLUMN "obs_cover";--> statement-breakpoint
ALTER TABLE "scans" DROP COLUMN "arch_scan";--> statement-breakpoint
ALTER TABLE "scans" DROP COLUMN "deploy_safe";--> statement-breakpoint
ALTER TABLE "scans" DROP COLUMN "prompt_trace";--> statement-breakpoint
ALTER TABLE "scans" DROP COLUMN "flow_value";--> statement-breakpoint
ALTER TABLE "scans" DROP COLUMN "dempster_shafer";--> statement-breakpoint
ALTER TABLE "scans" DROP COLUMN "constraint_solver";--> statement-breakpoint
ALTER TABLE "scans" DROP COLUMN "cross_language_taint";--> statement-breakpoint
ALTER TABLE "scans" DROP COLUMN "under_approximation";--> statement-breakpoint
ALTER TABLE "scans" DROP COLUMN "abstract_confidence";--> statement-breakpoint
ALTER TABLE "scans" DROP COLUMN "ai_consensus";--> statement-breakpoint
ALTER TABLE "scans" DROP COLUMN "time_aware_deps";--> statement-breakpoint
ALTER TABLE "scans" DROP COLUMN "product_reality";