export type RegulationFramework = "gdpr" | "pci_dss" | "soc2" | "hipaa" | "wcag" | "ccpa" | "lgpd" | "sox";

export type DataClassification = "pii" | "phi" | "pci" | "financial" | "credentials" | "session" | "consent" | "personal" | "biometric" | "location";

export interface ComplianceRule {
  id: string;
  framework: RegulationFramework;
  clause: string;
  title: string;
  description: string;
  severity: "critical" | "high" | "medium" | "low";
  dataClassification: DataClassification[];
  detectionType: "provenance" | "pattern" | "missing_implementation" | "config_check";
  patterns: string[];
  excludePatterns?: string[];
  contextPatterns?: string[];
  requiredControls: string[];
  fixAdvice: string;
  penaltyMaxEur?: number;
}

export interface ComplianceFinding {
  id: string;
  ruleId: string;
  framework: RegulationFramework;
  clause: string;
  title: string;
  description: string;
  severity: "critical" | "high" | "medium" | "low";
  dataClassification: DataClassification;
  file: string;
  line: number;
  column: number;
  code: string;
  provenancePath: string[];
  riskLevel: "low" | "medium" | "high" | "critical";
  penaltyEstimateEur?: number;
  requiredControls: string[];
  fixAdvice: string;
}

export const REGULATION_RULES: ComplianceRule[] = [
  // ══════════════════════════════════════════════════════════════════
  // GDPR — General Data Protection Regulation (EU 2016/679)
  // ══════════════════════════════════════════════════════════════════
  {
    id: "GDPR-001",
    framework: "gdpr",
    clause: "Art. 5(1)(c)",
    title: "Data minimization — excessive PII collection",
    description: "GDPR Article 5(1)(c) requires personal data to be adequate, relevant, and limited to what is necessary. Collecting special category data (race, ethnicity, politics, religion, biometrics) or excessive PII fields without explicit legal basis violates data minimization.",
    severity: "high",
    dataClassification: ["pii", "personal", "biometric"],
    detectionType: "pattern",
    patterns: [
      "req\\.body\\.ssn", "req\\.body\\.socialSecurity", "req\\.body\\.ethnicity",
      "req\\.body\\.race", "req\\.body\\.political", "req\\.body\\.religion",
      "req\\.body\\.sexual", "req\\.body\\.biometric", "req\\.body\\.genetic",
      "body\\.ssn", "body\\.socialSecurity", "body\\.ethnicity",
      "body\\.race", "body\\.political", "body\\.religion",
      "\\.ssn\\s*:", "\\.social_security\\s*:", "\\.ethnicity\\s*:",
    ],
    requiredControls: ["data_minimization", "legal_basis_check", "pii_inventory", "dpias"],
    fixAdvice: "Remove collection of special category data unless you have explicit Article 9 legal basis. Conduct a Data Protection Impact Assessment (DPIA). Collect only fields essential for the service. Document the legal basis for each data field per Article 6.",
    penaltyMaxEur: 20000000,
  },
  {
    id: "GDPR-002",
    framework: "gdpr",
    clause: "Art. 6",
    title: "Lawfulness of processing — missing legal basis",
    description: "GDPR Article 6 requires all personal data processing to have a valid legal basis: consent, contract performance, legal obligation, vital interests, public task, or legitimate interests. Processing without documented legal basis violates the principle of lawfulness.",
    severity: "high",
    dataClassification: ["pii", "personal", "consent"],
    detectionType: "missing_implementation",
    patterns: [
      "legalBasis", "legal_basis", "lawfulBasis",
      "processingBasis", "processing_basis",
      "consent.*record", "legitimate.*interest",
      "data.*processing.*agreement", "dpa",
      "privacy.*notice", "fair.*processing.*notice",
    ],
    requiredControls: ["legal_basis_documentation", "privacy_notice", "lawful_processing_check", "legitimate_interest_assessment"],
    fixAdvice: "Document the legal basis for each processing activity. For consent: implement freely-given, specific, informed, unambiguous opt-in. For legitimate interests: conduct a Legitimate Interests Assessment (LIA). Publish a clear privacy notice listing all processing purposes and legal bases.",
    penaltyMaxEur: 20000000,
  },
  {
    id: "GDPR-003",
    framework: "gdpr",
    clause: "Art. 7",
    title: "Consent conditions — invalid consent mechanism",
    description: "GDPR Article 7 requires consent to be freely given, specific, informed, and unambiguous. Silence, pre-ticked boxes, or inactivity does not constitute valid consent. Withdrawal must be as easy as giving consent.",
    severity: "critical",
    dataClassification: ["consent", "personal"],
    detectionType: "pattern",
    patterns: [
      "checked\\s*=\\s*true", "defaultChecked", "prechecked",
      "pre-checked", "pre_checked", "opt.*out.*default",
      "consent.*implicit", "implied.*consent",
      "silence.*consent", "presume.*consent",
      "consent.*checkbox[^)]*checked",
    ],
    contextPatterns: ["consent", "gdpr", "cookie"],
    requiredControls: ["explicit_opt_in", "granular_consent", "consent_withdrawal_mechanism", "consent_records"],
    fixAdvice: "Replace pre-ticked checkboxes with unticked opt-in boxes. Consent must be granular per purpose. Implement a consent withdrawal UI that is as easy as giving consent (same number of clicks). Record consent with timestamp, version, and user ID. Never use implied consent for non-essential processing.",
    penaltyMaxEur: 20000000,
  },
  {
    id: "GDPR-004",
    framework: "gdpr",
    clause: "Art. 17",
    title: "Right to erasure — no deletion mechanism",
    description: "GDPR Article 17 gives data subjects the right to obtain erasure of personal data without undue delay. The controller must also inform other controllers processing the data. Exceptions include legal obligation, public health, research, and legal claims.",
    severity: "high",
    dataClassification: ["pii", "personal", "credentials"],
    detectionType: "missing_implementation",
    patterns: [
      "router\\.delete\\(.*user", "router\\.delete\\(.*account",
      "app\\.delete\\(.*user", "app\\.delete\\(.*account",
      "prisma\\..*\\.delete\\(", "DELETE FROM.*users",
      "deleteUser", "destroyUser", "removeUser",
      "deactivateAccount", "deleteAccount",
      "user\\.delete\\(", "account\\.delete\\(",
      "delete.*user.*by.*id", "delete.*account",
    ],
    requiredControls: ["user_deletion_endpoint", "data_erasure_procedure", "cascading_deletion", "controller_notification"],
    fixAdvice: "Implement `DELETE /users/:id` that removes all personal data with cascading deletion of related records. Provide confirmation and process within 30 days. Inform other controllers who process the data. Honor exceptions: legal obligation, public health, research, legal claims.",
    penaltyMaxEur: 20000000,
  },
  {
    id: "GDPR-005",
    framework: "gdpr",
    clause: "Art. 20",
    title: "Right to data portability — no export mechanism",
    description: "GDPR Article 20 gives users the right to receive personal data in a structured, commonly used, machine-readable format and to transmit it to another controller. Applications lacking data export violate this right.",
    severity: "medium",
    dataClassification: ["pii", "personal"],
    detectionType: "missing_implementation",
    patterns: [
      "exportUser", "exportData", "downloadData",
      "/export", "data/export", "user/export",
      "generateCSV", "generateJSON.*user",
      "portability", "dataPortability",
      "userData.*download", "export.*user.*data",
      "router\\.get\\(.*export", "app\\.get\\(.*export",
      "GET.*export", "/download.*data",
    ],
    requiredControls: ["data_export_endpoint", "machine_readable_format", "structured_format", "portability_api"],
    fixAdvice: "Implement `GET /users/:id/export` returning JSON/CSV with all personal data the user provided and data generated from their activity. Use structured, commonly used formats (JSON, CSV). Support direct transmission to another controller per Article 20(2). Authenticate requests.",
    penaltyMaxEur: 20000000,
  },
  {
    id: "GDPR-006",
    framework: "gdpr",
    clause: "Art. 25",
    title: "Data protection by design and default — missing safeguards",
    description: "GDPR Article 25 requires implementing technical and organizational measures to integrate data protection into processing activities. By default, only necessary data should be processed. This includes pseudonymization, minimization, and transparency measures.",
    severity: "high",
    dataClassification: ["pii", "personal", "biometric", "location"],
    detectionType: "missing_implementation",
    patterns: [
      "pseudonymiz", "pseudonymis",
      "dataProtectionByDesign", "privacyByDesign",
      "privacy-by-design", "data-protection-by-design",
      "minimization", "data_minimization",
      "privacy.*default", "data.*protect.*default",
      "pbd", "dpbd",
    ],
    requiredControls: ["privacy_by_design_policy", "pseudonymization", "data_minimization_defaults", "transparency_measures"],
    fixAdvice: "Implement data protection by design: pseudonymize data where possible, collect only data necessary for each purpose, set privacy-friendly defaults (no broad consent pre-checks), integrate safeguards into processing systems, document design choices.",
    penaltyMaxEur: 20000000,
  },
  {
    id: "GDPR-007",
    framework: "gdpr",
    clause: "Art. 30",
    title: "Records of processing activities (ROPA) — missing documentation",
    description: "GDPR Article 30 requires maintaining written records of all processing activities including: controller contact details, processing purposes, data categories, recipient categories, transfer information, retention periods, and security measures. Enterprises with <250 employees are exempt unless processing is high-risk.",
    severity: "low",
    dataClassification: ["pii", "personal"],
    detectionType: "missing_implementation",
    patterns: [
      "ropa", "Ropa", "ROPA",
      "record.*process.*activity", "records.*of.*processing",
      "processing.*register", "data.*flow.*map",
      "data.*inventory", "processing.*activity.*record",
      "privacy.*policy", "data.*protection.*policy",
    ],
    requiredControls: ["ropa_documentation", "data_flow_mapping", "data_inventory", "processing_register"],
    fixAdvice: "Create a ROPA document covering: controller/DPO contact details, processing purposes, legal basis, data categories, recipient categories (including third countries), retention schedules, and technical security measures. Update annually. Exemption for <250 employees unless high-risk processing (Art. 30(5)).",
    penaltyMaxEur: 10000000,
  },
  {
    id: "GDPR-008",
    framework: "gdpr",
    clause: "Art. 32",
    title: "Security of processing — missing technical measures",
    description: "GDPR Article 32 requires appropriate technical and organizational measures including: pseudonymization, encryption, confidentiality/integrity/availability/resilience of systems, ability to restore access in a timely manner, and regular testing of effectiveness.",
    severity: "critical",
    dataClassification: ["pii", "phi", "credentials", "personal"],
    detectionType: "provenance",
    patterns: [
      "prisma\\..*\\.create\\(.*email", "prisma\\..*\\.create\\(.*address",
      "prisma\\..*\\.create\\(.*phone", "INSERT INTO.*users.*VALUES",
      "db\\..*\\.insert\\(.*email", "db\\..*\\.insert\\(.*address",
      "insert.*into.*users", "\\.save\\(.*email",
      "mongoose\\(.*email", "mongodb.*email",
    ],
    requiredControls: ["encryption_at_rest", "pseudonymization", "resilience_testing", "access_restoration", "regular_security_testing"],
    fixAdvice: "Implement encryption at rest (AES-256), encryption in transit (TLS 1.2+), pseudonymization of personal data, regular security testing (penetration tests, vulnerability scans), incident response procedures, and backup/restore capabilities. Document all security measures.",
    penaltyMaxEur: 10000000,
  },
  {
    id: "GDPR-009",
    framework: "gdpr",
    clause: "Art. 33",
    title: "Breach notification — missing 72-hour notification procedure",
    description: "GDPR Article 33 requires controllers to notify the supervisory authority of a personal data breach within 72 hours of becoming aware. The notification must include: nature of breach, categories and approximate number of data subjects, contact details, likely consequences, and measures taken.",
    severity: "high",
    dataClassification: ["pii", "personal", "credentials"],
    detectionType: "missing_implementation",
    patterns: [
      "incident", "breach", "security.*incident",
      "dataBreach", "data_breach", "incidentResponse",
      "incident-response", "incident_response",
      "security.*alert", "breach.*notification",
      "alerting", "pagerduty", "opsgenie",
      "sentry", "datadog.*alert", "newRelic.*alert",
    ],
    requiredControls: ["incident_detection", "72hr_notification_procedure", "breach_response_plan", "security_monitoring", "dpo_contact"],
    fixAdvice: "Implement incident detection and alerting (Sentry, Datadog, PagerDuty). Create a breach notification procedure within 72 hours including: detection, containment, investigation, assessment of risk, notification to supervisory authority, and communication to data subjects if high risk (Art. 34).",
    penaltyMaxEur: 10000000,
  },
  {
    id: "GDPR-010",
    framework: "gdpr",
    clause: "Art. 35",
    title: "Data protection impact assessment (DPIA) — missing for high-risk processing",
    description: "GDPR Article 35 requires a DPIA for processing likely to result in high risk to natural persons, including: systematic profiling, large-scale processing of special category data, and systematic monitoring of publicly accessible areas. Failure to conduct a DPIA where required is a violation.",
    severity: "high",
    dataClassification: ["pii", "biometric", "location", "personal"],
    detectionType: "missing_implementation",
    patterns: [
      "dpia", "DPIA", "dataProtectionImpactAssessment",
      "pia", "privacyImpactAssessment",
      "privacy-impact-assessment", "data-protection-impact",
      "risk.*assessment.*data", "data.*protect.*impact",
    ],
    requiredControls: ["dpia_process", "high_risk_identification", "prior_consultation", "risk_assessment_methodology"],
    fixAdvice: "Conduct a DPIA before processing that is likely high risk: automated profiling with legal effects, large-scale special category data processing, or systematic monitoring. The DPIA must describe processing, necessity/proportionality, risks to rights, and mitigation measures. Consult supervisory authority if residual risks remain (Art. 36).",
    penaltyMaxEur: 10000000,
  },
  {
    id: "GDPR-011",
    framework: "gdpr",
    clause: "Art. 44",
    title: "International data transfer — PII leaving EU/EEA without safeguards",
    description: "GDPR Article 44 restricts transfers of personal data to third countries without adequate safeguards. Transfers are only permitted if there is an adequacy decision, Standard Contractual Clauses (SCCs), Binding Corporate Rules (BCRs), or an approved code of conduct.",
    severity: "high",
    dataClassification: ["pii", "personal"],
    detectionType: "provenance",
    patterns: [
      "fetch\\(.*email", "axios\\.post\\(.*user", "fetch\\(.*personal",
      "got\\(.*email", "fetch\\(.*address", "axios\\.post\\(.*address",
      "stripe\\.", "mixpanel", "amplitude", "intercom",
      "google-analytics", "gtag", "facebook-pixel",
      "hubspot\\.", "salesforce", "zendesk",
      "sendGrid", "sendgrid", "twilio", "mailchimp",
    ],
    requiredControls: ["scc_in_place", "adequacy_decision_check", "data_processing_agreement", "tia_assessment", "bcr_if_applicable"],
    fixAdvice: "Ensure all third-party data processors are covered by: EU adequacy decision for the destination country, or Standard Contractual Clauses (2021 SCCs) with Transfer Impact Assessment (TIA), or Binding Corporate Rules (BCRs). Sign Data Processing Agreements (DPAs). Document the transfer mechanism.",
    penaltyMaxEur: 20000000,
  },

  // ══════════════════════════════════════════════════════════════════
  // PCI-DSS v4.0 — Payment Card Industry Data Security Standard
  // ══════════════════════════════════════════════════════════════════
  {
    id: "PCI-001",
    framework: "pci_dss",
    clause: "Req 3.2.1",
    title: "Sensitive authentication data stored after authorization",
    description: "PCI-DSS v4.0 Requirement 3.2.1 (formerly 3.2 in v3.2.1) prohibits storage of sensitive authentication data after authorization. Full track data, card verification codes (CVV/CVC), and PINs must never be retained post-authorization. Storage of these values results in immediate non-compliance.",
    severity: "critical",
    dataClassification: ["pci", "financial"],
    detectionType: "provenance",
    patterns: [
      "cvv", "cvc", "ccv", "cardCode", "card_code",
      "creditCardNumber", "cardNumber", "card_number",
      "pan\\s*:", "cardNumber\\s*:", "card_number\\s*:",
      "ccNumber", "credit_card", "cardNo", "cardno",
      "track.*data", "track2", "track1",
      "full.*pan", "expiryDate", "expirationDate",
    ],
    requiredControls: ["tokenization", "cardholder_data_protection", "pci_compliant_gateway", "no_cvv_storage"],
    fixAdvice: "Never store full PAN, CVV/CVC, or track data after authorization. Use a PCI-compliant tokenization service (Stripe, Braintree, Square). Replace card data with tokens before storage. If PAN retention is needed for business reasons, render it unreadable per Requirement 3.5.1. Implement data retention and disposal policies.",
    penaltyMaxEur: 0,
  },
  {
    id: "PCI-002",
    framework: "pci_dss",
    clause: "Req 3.3",
    title: "Sensitive authentication data stored prior to or during authorization",
    description: "PCI-DSS v4.0 Requirement 3.3 strictly prohibits storage of sensitive authentication data (SAD) even prior to authorization. Full track data, card verification codes, and PINs must not be stored at any point. Only the PAN may be rendered unreadable and retained if required.",
    severity: "critical",
    dataClassification: ["pci", "financial"],
    detectionType: "provenance",
    patterns: [
      "cvv", "cvc", "track.*data", "track2", "pin.*block",
      "encryptedPIN", "pinBlock", "pin_data",
      "fullTrack", "trackData", "magstripe",
      "chip.*data", "emv.*data", "icc.*data",
      "cardSeq", "cardSequence",
    ],
    requiredControls: ["sad_not_stored", "tokenization", "pci_compliant_payment_form", "direct_post"],
    fixAdvice: "Never store SAD at any point in the transaction lifecycle. Use direct-post integration (Stripe Elements, Braintree Drop-in) that sends card data directly from the browser to the payment gateway without it touching your server. Validate with a PCI ASV scan.",
    penaltyMaxEur: 0,
  },
  {
    id: "PCI-003",
    framework: "pci_dss",
    clause: "Req 3.3.2",
    title: "SAD stored before authorization not encrypted",
    description: "PCI-DSS v4.0 Requirement 3.3.2 (new in v4.0) requires that any SAD stored electronically prior to authorization must be encrypted using strong cryptography. This was a best practice until March 2025 and is now mandatory.",
    severity: "critical",
    dataClassification: ["pci", "financial"],
    detectionType: "provenance",
    patterns: [
      "sad.*encrypt", "sensitive.*auth.*data",
      "encryptedSAD", "encrypted_sad",
      "temp.*card.*data", "transient.*card",
    ],
    requiredControls: ["sad_encryption", "strong_cryptography", "key_management", "pci_compliant_integration"],
    fixAdvice: "If SAD must be stored temporarily before authorization, encrypt it using strong cryptography (AES-256). However, the preferred approach is to avoid storing SAD entirely. Migrate to a direct-post integration that never exposes card data to your server.",
    penaltyMaxEur: 0,
  },
  {
    id: "PCI-004",
    framework: "pci_dss",
    clause: "Req 3.5.1",
    title: "PAN stored without rendering unreadable",
    description: "PCI-DSS v4.0 Requirement 3.5.1 requires PAN to be rendered unreadable anywhere it is stored using one-way hashing, truncation, index tokens, or encryption. Storing PAN in plaintext is a critical violation.",
    severity: "critical",
    dataClassification: ["pci", "financial"],
    detectionType: "provenance",
    patterns: [
      "pan\\s*:", "cardNumber\\s*:", "card_number\\s*:",
      "ccNumber", "credit_card", "cardNo",
      "stripe\\.charges\\.create\\(.*token",
      "stripe\\.paymentIntents\\.create\\(.*payment_method",
    ],
    requiredControls: ["pan_unreadable", "one_way_hashing", "truncation", "tokenization", "encryption"],
    fixAdvice: "Render PAN unreadable using one of: truncation (store last 4 digits only), one-way hashing with keyed cryptographic hash (per 3.5.1.1), index tokens, or strong encryption (AES-256). Never store full PAN in plaintext. Mask PAN in logs and displays.",
    penaltyMaxEur: 0,
  },
  {
    id: "PCI-005",
    framework: "pci_dss",
    clause: "Req 3.5.1.1",
    title: "PAN hashed without keyed cryptographic hash",
    description: "PCI-DSS v4.0 Requirement 3.5.1.1 (new in v4.0) requires that when hashing PAN, a keyed cryptographic hash (HMAC) must be used. Simple hashing without a key is insufficient to prevent rainbow table attacks on the limited PAN keyspace.",
    severity: "high",
    dataClassification: ["pci", "financial"],
    detectionType: "pattern",
    patterns: [
      "hash\\(.*pan", "hash\\(.*card", "md5\\(.*pan",
      "sha1\\(.*pan", "sha256\\(.*pan",
      "bcrypt\\(.*pan", "crypto.*createHash.*pan",
      "crypto.*hash.*card",
    ],
    excludePatterns: ["hmac", "createHmac", "keyed.*hash", "salted.*hash"],
    requiredControls: ["keyed_cryptographic_hash", "hmac_implementation", "key_management"],
    fixAdvice: "Replace simple hashing of PAN with HMAC using a strong secret key: `crypto.createHmac('sha256', secretKey).update(pan).digest('hex')`. Manage the HMAC key securely (HSM, KMS). Never use plain SHA/MD5 for PAN hashing. Truncation is preferred over hashing for display purposes.",
    penaltyMaxEur: 0,
  },
  {
    id: "PCI-006",
    framework: "pci_dss",
    clause: "Req 4.2.1",
    title: "PAN transmitted without strong cryptography",
    description: "PCI-DSS v4.0 Requirement 4.2.1 requires PAN to be protected with strong cryptography during transmission over open/public networks. TLS 1.2 or higher is required. Sending cardholder data over HTTP, TLS 1.0/1.1, or without encryption is a critical violation.",
    severity: "critical",
    dataClassification: ["pci", "financial"],
    detectionType: "pattern",
    patterns: [
      "http://.*payment", "http://.*checkout", "http://.*billing",
      "http://.*card", "http://.*charge",
      "http://.*stripe", "http://.*braintree",
      "http\\.createServer", "http://",
    ],
    requiredControls: ["tls_1_2_minimum", "hsts", "certificate_management", "encrypted_payload"],
    fixAdvice: "Ensure all systems transmitting cardholder data use TLS 1.2+. Redirect HTTP to HTTPS. Implement HSTS with `max-age=31536000; includeSubDomains`. Disable TLS 1.0/1.1. Use only strong cipher suites. Validate certificates. Never send raw PAN over non-TLS connections.",
    penaltyMaxEur: 0,
  },
  {
    id: "PCI-007",
    framework: "pci_dss",
    clause: "Req 6.6",
    title: "Public-facing web applications not protected against known attacks",
    description: "PCI-DSS v4.0 Requirement 6.6 requires public-facing web applications to be protected against known attacks including cross-site scripting (XSS), SQL injection, CSRF, and authentication bypass. This includes code review, WAF, and vulnerability scanning.",
    severity: "critical",
    dataClassification: ["pci", "financial"],
    detectionType: "provenance",
    patterns: [
      "res\\.render\\(.*user", "res\\.render\\(.*req",
      "dangerouslySetInnerHTML", "v-html",
      "res\\.send\\(.*req\\.body", "res\\.send\\(.*user",
      "\\.innerHTML\\s*=\\s*.*req", "\\.innerHTML\\s*=\\s*.*user",
      "eval\\(", "Function\\(",
    ],
    requiredControls: ["xss_prevention", "csp_headers", "input_sanitization", "waf", "code_review", "vulnerability_scanning"],
    fixAdvice: "Apply Content Security Policy (CSP) headers on all pages: `default-src 'self'`. Use output encoding for all user-controlled data. Sanitize inputs with DOMPurify. Deploy a WAF (Cloudflare, AWS WAF, ModSecurity). Conduct annual code reviews and quarterly vulnerability scans per PCI-DSS 11.3.",
    penaltyMaxEur: 0,
  },
  {
    id: "PCI-008",
    framework: "pci_dss",
    clause: "Req 10.2.1",
    title: "Missing audit logs for cardholder data access",
    description: "PCI-DSS v4.0 Requirement 10.2.1 requires audit logs for all access to cardholder data, all actions by privileged users, all authentication events, and all invalid access attempts. Missing logs prevent anomaly detection and forensic investigation.",
    severity: "high",
    dataClassification: ["pci", "financial"],
    detectionType: "missing_implementation",
    patterns: [
      "audit.*log", "auditLog", "access.*log", "payment.*log",
      "charge\\.log", "transaction.*log",
      "logger\\.info\\(.*payment", "logger\\.info\\(.*charge",
      "logger\\.info\\(.*transaction", "logger\\.info\\(.*billing",
    ],
    requiredControls: ["audit_logging", "access_monitoring", "log_immutability", "anomaly_detection"],
    fixAdvice: "Implement comprehensive audit logging for: all access to cardholder data, privileged actions, authentication successes/failures, and anomaly events. Logs must be immutable (append-only). Include user ID, event type, timestamp, source IP, and affected data. Integrate with SIEM for automated monitoring.",
    penaltyMaxEur: 0,
  },
  {
    id: "PCI-009",
    framework: "pci_dss",
    clause: "Req 10.3",
    title: "Audit logs not protected from destruction or modification",
    description: "PCI-DSS v4.0 Requirement 10.3 requires audit logs to be protected from destruction and unauthorized modification. Logs must be immutable/append-only, secured with access controls, and backed up to prevent single points of failure.",
    severity: "high",
    dataClassification: ["pci", "financial"],
    detectionType: "config_check",
    patterns: [
      "log\\.rotate", "truncate.*log", "clear.*log",
      "delete.*log", "remove.*log", "log.*cleanup",
    ],
    excludePatterns: ["archive", "backup", "compress", "retention"],
    requiredControls: ["immutable_logs", "log_access_control", "log_backup", "log_integrity_monitoring"],
    fixAdvice: "Implement append-only logging (e.g., AWS CloudWatch with immutable log groups, Write-Once-Read-Many storage). Restrict log access to authorized personnel only. Implement log integrity monitoring (hash chaining). Back up logs offsite. Retain logs per Requirement 10.5.1.",
    penaltyMaxEur: 0,
  },
  {
    id: "PCI-010",
    framework: "pci_dss",
    clause: "Req 10.4.1",
    title: "Audit logs not reviewed daily",
    description: "PCI-DSS v4.0 Requirement 10.4.1 requires daily review of audit logs for all critical system components. New in v4.0, automated log review mechanisms (10.4.1.1) become mandatory March 31, 2025. Manual daily review is acceptable until then.",
    severity: "high",
    dataClassification: ["pci", "financial"],
    detectionType: "missing_implementation",
    patterns: [
      "log.*review", "logReview", "audit.*review",
      "daily.*log", "log.*analysis", "log.*monitor",
      "siem", "SIEM", "splunk", "datadog",
      "elk.*log", "elastic.*log", "logstash",
    ],
    requiredControls: ["daily_log_review", "automated_log_analysis", "siem_integration", "alerting_rules"],
    fixAdvice: "Implement daily audit log review procedures. Configure automated log analysis tools (SIEM) with alerting for suspicious events. By March 2025, automated mechanisms per PCI-DSS 10.4.1.1 are mandatory. Retain log review records for 12 months. Document review responsibilities.",
    penaltyMaxEur: 0,
  },
  {
    id: "PCI-011",
    framework: "pci_dss",
    clause: "Req 10.5.1",
    title: "Audit log history retained for insufficient period",
    description: "PCI-DSS v4.0 Requirement 10.5.1 requires audit log history to be retained for at least 12 months, with a minimum of 3 months readily available for immediate analysis. Shorter retention periods violate forensic investigation requirements.",
    severity: "medium",
    dataClassification: ["pci", "financial"],
    detectionType: "config_check",
    patterns: [
      "logRetention", "log_retention", "retention.*days",
      "TTL.*log", "expireAfterSeconds.*log",
      "retention.*log", "log.*expire",
    ],
    excludePatterns: ["365", "366", "12.*month", "1.*year"],
    requiredControls: ["12_month_log_retention", "3_month_online", "log_archival", "retention_policy"],
    fixAdvice: "Configure audit log retention for at least 12 months with 3 months immediately available (online). Archive older logs to cost-effective storage (S3 Glacier, Azure Archive). Implement log rotation that archives, not deletes. Document the retention policy and enforce with automated tools.",
    penaltyMaxEur: 0,
  },

  // ══════════════════════════════════════════════════════════════════
  // SOC 2 — AICPA Trust Services Criteria (Security category)
  // ══════════════════════════════════════════════════════════════════
  {
    id: "SOC2-001",
    framework: "soc2",
    clause: "CC6.1",
    title: "Logical access security — insufficient access controls",
    description: "SOC 2 CC6.1 requires logical access security for software, infrastructure, and architectures. Systems must restrict logical access, use encryption to protect data at rest and in transit, and protect encryption keys. Missing access controls on sensitive endpoints violate this criterion.",
    severity: "high",
    dataClassification: ["credentials", "session", "pii", "pci"],
    detectionType: "pattern",
    patterns: [
      "router\\.get\\(.*admin", "router\\.post\\(.*admin",
      "router\\.get\\(.*internal", "router\\.get\\(.*dashboard",
      "router\\.get\\(.*settings", "router\\.get\\(.*users",
    ],
    contextPatterns: ["authMiddleware", "requireAuth", "authenticate", "verifyToken", "isAuthenticated"],
    requiredControls: ["access_control", "authentication_middleware", "encryption_key_protection", "rbac"],
    fixAdvice: "Protect all internal/admin endpoints with authentication middleware. Implement RBAC. Protect encryption keys using HSM or KMS (AWS KMS, HashiCorp Vault). Use encryption for data at rest and in transit. Conduct quarterly access reviews. Log all access attempts.",
    penaltyMaxEur: 0,
  },
  {
    id: "SOC2-002",
    framework: "soc2",
    clause: "CC6.3",
    title: "Role-based access and least privilege not enforced",
    description: "SOC 2 CC6.3 requires access rights to be based on job requirements using the principle of least privilege. Access rights must be reviewed at least quarterly. Excessive permissions or lack of access reviews violate this criterion.",
    severity: "high",
    dataClassification: ["credentials", "session", "pii"],
    detectionType: "missing_implementation",
    patterns: [
      "role.*admin", "roleAdmin", "isAdmin",
      "admin.*role", "super.*user", "superuser",
      "permission.*level", "user.*role",
      "rbac", "Rbac", "RBAC",
      "access.*control.*list", "acl",
    ],
    requiredControls: ["role_based_access", "least_privilege", "quarterly_access_review", "permission_audit"],
    fixAdvice: "Implement RBAC with granular permissions. Assign the minimum access needed for each role. Conduct quarterly access reviews (documented). Revoke orphaned accounts immediately. Use just-in-time (JIT) privileged access. Separate admin from standard user roles.",
    penaltyMaxEur: 0,
  },
  {
    id: "SOC2-003",
    framework: "soc2",
    clause: "CC6.4",
    title: "Physical access restrictions — missing controls",
    description: "SOC 2 CC6.4 requires physical access restrictions to protected assets including badge readers, mantrap entry, visitor logs, and secure destruction of media. While code-level detection is limited, applications deployed in shared or uncontrolled physical environments should assess physical security.",
    severity: "medium",
    dataClassification: ["pii", "pci", "credentials"],
    detectionType: "config_check",
    patterns: [
      "cloud.*provider", "aws.*region", "gcp.*region",
      "azure.*region", "datacenter", "data.*center",
      "colocation", "server.*room",
    ],
    requiredControls: ["physical_access_controls", "visitor_management", "media_destruction", "environmental_controls"],
    fixAdvice: "Ensure your hosting provider has physical security controls: badge readers or biometric access, mantrap entry, 24/7 surveillance, visitor logs, and secure media destruction (degaussing, shredding). Review SOC 2 Type II reports of cloud providers. Implement environmental protections (fire suppression, climate control, UPS).",
    penaltyMaxEur: 0,
  },
  {
    id: "SOC2-004",
    framework: "soc2",
    clause: "CC6.5",
    title: "Logical access to protected assets — missing authentication",
    description: "SOC 2 CC6.5 requires authentication for all access points to protected assets including MFA for external access. Applications that allow access to sensitive data without authentication or without MFA on admin interfaces violate this criterion.",
    severity: "critical",
    dataClassification: ["pii", "pci", "credentials", "financial"],
    detectionType: "pattern",
    patterns: [
      "router\\.get\\(.*data", "router\\.post\\(.*data",
      "app\\.get\\(.*api", "app\\.post\\(.*api",
      "res\\.json\\(.*data", "res\\.send\\(.*data",
    ],
    contextPatterns: ["authMiddleware", "requireAuth", "authenticate", "verifyToken", "isAuthenticated"],
    requiredControls: ["authentication_for_all", "mfa", "access_point_security", "session_management"],
    fixAdvice: "Require authentication on all data access endpoints. Implement MFA for all external access and privileged accounts. Use secure session management with short timeouts. Validate authentication on every request, not just at first access. Implement rate limiting on authentication endpoints.",
    penaltyMaxEur: 0,
  },
  {
    id: "SOC2-005",
    framework: "soc2",
    clause: "CC6.6",
    title: "Security against threats from outside system boundaries",
    description: "SOC 2 CC6.6 requires security against threats from outside system boundaries including firewalls, intrusion detection/prevention systems (IDS/IPS), and VPN or zero-trust network access for remote access to protected assets.",
    severity: "high",
    dataClassification: ["pii", "pci", "credentials", "financial", "personal"],
    detectionType: "config_check",
    patterns: [
      "http\\.createServer", "http://",
      "firewall", "waf", "cloudflare",
      "securityGroup", "security_group",
      "network.*acl", "nacl",
    ],
    requiredControls: ["firewall_configuration", "ids_ips", "vpn_zero_trust", "network_segmentation", "waf"],
    fixAdvice: "Deploy firewalls to restrict inbound/outbound traffic to only necessary ports and protocols. Implement IDS/IPS (Snort, Suricata, AWS GuardDuty). Use VPN or zero-trust architecture (Zscaler, Cloudflare Access) for remote access. Segment networks to isolate sensitive systems. Deploy WAF for web applications.",
    penaltyMaxEur: 0,
  },
  {
    id: "SOC2-006",
    framework: "soc2",
    clause: "CC6.7",
    title: "Information transmission and movement — no DLP or encryption controls",
    description: "SOC 2 CC6.7 requires restricting the transmission, movement, and removal of information. Data Loss Prevention (DLP), TLS encryption, removable media controls, and Mobile Device Management (MDM) are expected to prevent unauthorized data exfiltration.",
    severity: "high",
    dataClassification: ["pii", "pci", "credentials", "personal"],
    detectionType: "missing_implementation",
    patterns: [
      "dlp", "DLP", "dataLossPrevention",
      "data.*loss.*prevent", "data_exfil",
      "removable.*media", "usb.*control",
      "mdm", "mobileDeviceManagement",
      "tls", "TLS", "https", "HTTPS",
    ],
    requiredControls: ["dlp_solution", "tls_enforcement", "removable_media_controls", "mdm_policy"],
    fixAdvice: "Implement DLP monitoring (Symantec DLP, Microsoft Purview, BetterCloud). Enforce TLS for all data in transit. Restrict or disable removable media on systems with sensitive data. Implement MDM for mobile access (Jamf, Intune, Workspace ONE). Monitor for unusual data transfer volumes.",
    penaltyMaxEur: 0,
  },
  {
    id: "SOC2-007",
    framework: "soc2",
    clause: "CC7.2",
    title: "Monitoring — no anomaly detection or SIEM",
    description: "SOC 2 CC7.2 requires monitoring system components for anomalies and indicators of compromise. SIEM/log aggregation, alerting rules, and periodic review procedures must detect unauthorized access, credential misuse, and suspicious activity.",
    severity: "high",
    dataClassification: ["credentials", "session", "pii"],
    detectionType: "missing_implementation",
    patterns: [
      "logger\\.info\\(.*login", "logger\\.info\\(.*logout",
      "logger\\.warn\\(.*failed.*auth", "logger\\.info\\(.*password.*reset",
      "logger\\.info\\(.*role.*change", "logger\\.info\\(.*permission",
      "logger\\.info\\(.*config.*change", "logger\\.info\\(.*setting.*update",
      "audit\\.log", "security.*event",
      "log.*attempt", "log.*access",
    ],
    requiredControls: ["security_event_logging", "siem_integration", "log_monitoring", "alerting", "anomaly_detection"],
    fixAdvice: "Implement structured security event logging for: authentication successes/failures, privilege changes, configuration changes, and data access. Send logs to a SIEM (Datadog, Splunk, ELK, Sentinel). Set up alerts for: multiple failed logins, privilege escalation, off-hours access, and unusual data volumes.",
    penaltyMaxEur: 0,
  },
  {
    id: "SOC2-008",
    framework: "soc2",
    clause: "CC7.3",
    title: "Security incident response — no documented plan or testing",
    description: "SOC 2 CC7.3 requires a documented security incident response plan that is tested at least annually. The plan must include: detection, containment, eradication, recovery, and lessons learned. Missing or untested incident response procedures violate this criterion.",
    severity: "high",
    dataClassification: ["pii", "pci", "credentials", "personal"],
    detectionType: "missing_implementation",
    patterns: [
      "incident.*response", "incidentResponse",
      "security.*incident", "breach.*response",
      "ir.*plan", "incident.*plan",
      "tabletop.*exercise", "incident.*test",
      "containment.*procedure", "eradication.*plan",
    ],
    requiredControls: ["incident_response_plan", "annual_testing", "tabletop_exercise", "lessons_learned_process"],
    fixAdvice: "Create a documented incident response plan covering: preparation, detection & analysis, containment/eradication/recovery, and post-incident activity. Test the plan at least annually (tabletop exercises or full simulations). Document and track lessons learned. Assign incident response roles (commander, comms, legal, forensics).",
    penaltyMaxEur: 0,
  },
  {
    id: "SOC2-009",
    framework: "soc2",
    clause: "CC7.4",
    title: "Breach notification — no documented notification process",
    description: "SOC 2 CC7.4 requires a documented breach identification and notification process that meets legal, regulatory, and contractual obligations. This includes identifying affected parties, coordinating with legal counsel, and notifying within required timeframes.",
    severity: "high",
    dataClassification: ["pii", "pci", "credentials", "personal"],
    detectionType: "missing_implementation",
    patterns: [
      "breach.*notif", "breachNotif",
      "data.*breach.*procedure",
      "notif.*obligation", "regulatory.*notification",
      "data.*protect.*authority", "supervisory.*authority",
    ],
    requiredControls: ["breach_notification_process", "legal_coordination", "regulatory_compliance_check", "affected_party_identification"],
    fixAdvice: "Document a breach notification process that identifies: who needs to be notified (regulators, affected parties, law enforcement), notification timeframes (e.g., GDPR 72 hours), required content, and responsible parties. Coordinate with legal counsel. Maintain a notification template. Test the process during incident response exercises.",
    penaltyMaxEur: 0,
  },

  // ══════════════════════════════════════════════════════════════════
  // HIPAA — 45 CFR Part 164 (Security Rule)
  // ══════════════════════════════════════════════════════════════════
  {
    id: "HIPAA-001",
    framework: "hipaa",
    clause: "164.308(a)(1)(ii)(A)",
    title: "Risk analysis — no assessment of ePHI risks",
    description: "HIPAA 164.308(a)(1)(ii)(A) requires an accurate and thorough assessment of potential risks and vulnerabilities to the confidentiality, integrity, and availability of ePHI. Organizations without a formal risk analysis are non-compliant.",
    severity: "critical",
    dataClassification: ["phi", "personal"],
    detectionType: "missing_implementation",
    patterns: [
      "risk.*assessment", "risk.*analysis",
      "security.*assessment", "risk.*management",
      "hipaa.*risk", "ePHI.*risk",
      "security.*risk", "vulnerability.*assessment",
    ],
    requiredControls: ["formal_risk_analysis", "risk_mitigation_plan", "annual_reassessment", "documented_methodology"],
    fixAdvice: "Conduct a formal HIPAA Security Risk Assessment following NIST SP 800-30 or HHS guidance. Identify potential risks to ePHI confidentiality, integrity, and availability. Document threats, vulnerabilities, likelihood, and impact. Implement mitigation measures. Reassess annually or after environmental changes. Retain documentation for 6 years.",
    penaltyMaxEur: 50000,
  },
  {
    id: "HIPAA-002",
    framework: "hipaa",
    clause: "164.308(a)(1)(ii)(B)",
    title: "Risk management — insufficient security measures",
    description: "HIPAA 164.308(a)(1)(ii)(B) requires implementing security measures sufficient to reduce risks and vulnerabilities to a reasonable and appropriate level. A risk analysis without corresponding risk mitigation is insufficient.",
    severity: "high",
    dataClassification: ["phi", "personal"],
    detectionType: "missing_implementation",
    patterns: [
      "risk.*mitigation", "riskMitigation",
      "security.*measure", "security.*control",
      "safeguard", "protective.*measure",
      "corrective.*action", "remediation.*plan",
    ],
    requiredControls: ["risk_management_plan", "security_controls_implementation", "remediation_tracking", "residual_risk_acceptance"],
    fixAdvice: "Implement a risk management plan that addresses each identified risk. Assign remediation owners and deadlines. Track remediation progress. Accept residual risk with formal sign-off. Implement administrative, physical, and technical safeguards. Document all risk management decisions and rationale.",
    penaltyMaxEur: 50000,
  },
  {
    id: "HIPAA-003",
    framework: "hipaa",
    clause: "164.308(a)(5)(ii)(A)",
    title: "Security awareness and training — no workforce training program",
    description: "HIPAA 164.308(a)(5)(ii)(A) requires a security awareness and training program for all workforce members, including management. Regular training on HIPAA requirements, password management, phishing awareness, and incident reporting is mandatory.",
    severity: "high",
    dataClassification: ["phi", "personal", "credentials"],
    detectionType: "missing_implementation",
    patterns: [
      "security.*train", "hipaa.*train",
      "awareness.*program", "phishing.*train",
      "privacy.*train", "workforce.*train",
      "annual.*train.*security", "compliance.*train",
    ],
    requiredControls: ["security_awareness_program", "annual_training", "phishing_simulations", "training_records"],
    fixAdvice: "Implement a security awareness program covering: HIPAA Privacy and Security Rules, password policies, phishing awareness, social engineering, incident reporting, and mobile device security. Conduct training at hire and annually. Track completion with sign-offs. Conduct phishing simulations quarterly.",
    penaltyMaxEur: 50000,
  },
  {
    id: "HIPAA-004",
    framework: "hipaa",
    clause: "164.310(a)(2)(i)",
    title: "Facility access controls — no physical security for ePHI systems",
    description: "HIPAA 164.310(a)(2)(i) requires facility access controls to limit physical access to electronic information systems and the facilities in which they are housed. This includes contingency operations, facility security plan, access control/validation, and maintenance records.",
    severity: "medium",
    dataClassification: ["phi", "personal"],
    detectionType: "config_check",
    patterns: [
      "data.*center", "server.*room", "colocation",
      "cloud.*host", "aws.*ec2", "gcp.*compute",
      "azure.*vm", "on.*prem", "on-prem",
    ],
    requiredControls: ["facility_security_plan", "physical_access_controls", "visitor_logs", "maintenance_records"],
    fixAdvice: "Limit physical access to systems housing ePHI. Implement: facility security plan, access control systems (badge/biometric), visitor logs and escorts, maintenance records, and contingency access procedures. For cloud systems, review provider's SOC 2 Type II or HIPAA BAA covering physical security.",
    penaltyMaxEur: 50000,
  },
  {
    id: "HIPAA-005",
    framework: "hipaa",
    clause: "164.312(a)(1)",
    title: "Access control — no unique user identification or emergency access",
    description: "HIPAA 164.312(a)(1) requires technical policies to allow ePHI access only to authorized persons or software programs. Required specifications: unique user ID, emergency access procedure. Addressable: automatic logoff, encryption/decryption. Missing any of these violates the Security Rule.",
    severity: "critical",
    dataClassification: ["phi", "personal"],
    detectionType: "missing_implementation",
    patterns: [
      "unique.*user.*id", "uniqueUserID",
      "emergency.*access", "break.*glass",
      "auto.*logoff", "auto.*logout",
      "session.*timeout", "inactivity.*timeout",
      "access.*control", "authorization.*check",
    ],
    requiredControls: ["unique_user_ids", "emergency_access_procedure", "automatic_logoff", "encryption_decryption"],
    fixAdvice: "Implement unique user IDs for every user with ePHI access. Create an emergency access (break-glass) procedure for crisis situations. Implement automatic logoff after 15 minutes of inactivity. Enable encryption/decryption mechanisms. Enforce strict authorization checks on all ePHI access.",
    penaltyMaxEur: 50000,
  },
  {
    id: "HIPAA-006",
    framework: "hipaa",
    clause: "164.312(a)(2)(iv)",
    title: "Encryption and decryption (addressable) — no mechanism for ePHI",
    description: "HIPAA 164.312(a)(2)(iv) (addressable) requires implementing a mechanism to encrypt and decrypt ePHI. While addressable, failure to implement encryption must be documented with an equivalent alternative measure. Lack of encryption for ePHI at rest is a common finding in HIPAA audits.",
    severity: "critical",
    dataClassification: ["phi", "personal"],
    detectionType: "provenance",
    patterns: [
      "prisma\\..*\\.create\\(.*health", "db\\..*\\.insert\\(.*medical",
      "INSERT INTO.*patients", "INSERT INTO.*health",
      "\\.save\\(.*health", "\\.save\\(.*patient",
      "mongoose\\(.*Health", "mongodb.*patient",
    ],
    requiredControls: ["encryption_at_rest", "phi_column_encryption", "key_rotation", "backup_encryption"],
    fixAdvice: "Encrypt ePHI at rest using AES-256. Use database-level transparent data encryption (TDE). Encrypt all backups. Implement key rotation every 12 months. If encryption is not implemented, document the equivalent alternative measure and the rationale per the addressable implementation specification.",
    penaltyMaxEur: 50000,
  },
  {
    id: "HIPAA-007",
    framework: "hipaa",
    clause: "164.312(b)",
    title: "Audit controls — no recording of ePHI activity",
    description: "HIPAA 164.312(b) requires hardware, software, and procedural mechanisms to record and examine activity in systems containing or using ePHI. Applications handling health data without audit logging of all ePHI access are non-compliant.",
    severity: "high",
    dataClassification: ["phi", "personal"],
    detectionType: "missing_implementation",
    patterns: [
      "audit.*phi", "phi.*audit", "phi.*log",
      "health.*audit", "medical.*audit",
      "logger\\.info\\(.*phi", "logger\\.info\\(.*health",
      "logger\\.info\\(.*patient", "logger\\.info\\(.*medical",
    ],
    requiredControls: ["phi_audit_log", "access_recording", "log_analysis", "violation_alerting"],
    fixAdvice: "Implement audit logging for every ePHI access: who accessed it, when, from where (IP), what action (read/write/delete), and which record. Retain logs for at least 6 years per HIPAA requirements. Regularly review logs for anomalous access patterns. Implement automated alerting for violations.",
    penaltyMaxEur: 50000,
  },
  {
    id: "HIPAA-008",
    framework: "hipaa",
    clause: "164.312(c)(1)",
    title: "Integrity controls — no protection against improper ePHI alteration",
    description: "HIPAA 164.312(c)(1) requires policies and procedures to protect ePHI from improper alteration or destruction. This includes electronic mechanisms to corroborate that ePHI has not been altered or destroyed in an unauthorized manner.",
    severity: "high",
    dataClassification: ["phi", "personal"],
    detectionType: "missing_implementation",
    patterns: [
      "integrity.*check", "data.*integrity",
      "checksum", "hash.*verify", "digital.*signature",
      "audit.*trail", "version.*history",
      "immutable.*log", "append.*only",
    ],
    requiredControls: ["integrity_controls", "checksum_verification", "digital_signatures", "audit_trails"],
    fixAdvice: "Implement integrity controls to ensure ePHI is not improperly altered or destroyed. Use checksums or digital signatures to verify data integrity. Maintain version history of ePHI records. Use append-only audit logs. Implement access controls to prevent unauthorized modification.",
    penaltyMaxEur: 50000,
  },
  {
    id: "HIPAA-009",
    framework: "hipaa",
    clause: "164.312(d)",
    title: "Person/entity authentication — no verification mechanism",
    description: "HIPAA 164.312(d) requires procedures to verify that a person or entity seeking access to ePHI is the one claimed. This includes authentication mechanisms such as passwords, biometrics, tokens, or two-factor authentication.",
    severity: "critical",
    dataClassification: ["phi", "personal", "credentials"],
    detectionType: "missing_implementation",
    patterns: [
      "password.*reset", "passwordReset",
      "authenticate", "login", "signIn",
      "mfa", "twoFactor", "2fa", "totp",
      "biometric", "fingerprint", "faceId",
      "sso", "singleSignOn", "oauth", "saml",
    ],
    requiredControls: ["authentication_mechanism", "mfa_for_phi_access", "password_policy", "session_management"],
    fixAdvice: "Implement strong authentication for all ePHI access. Enforce MFA/TOTP for all users accessing ePHI. Require strong passwords (12+ characters, complexity). Implement account lockout after failed attempts. Use secure session management with short timeouts. Consider biometric authentication for mobile access.",
    penaltyMaxEur: 50000,
  },
  {
    id: "HIPAA-010",
    framework: "hipaa",
    clause: "164.312(e)(1)",
    title: "Transmission security — no protection for ePHI in transit",
    description: "HIPAA 164.312(e)(1) requires technical security measures to guard against unauthorized access to ePHI transmitted over electronic communications networks. Addressable: integrity controls, encryption. Sending ePHI over unencrypted channels violates this standard.",
    severity: "critical",
    dataClassification: ["phi", "personal"],
    detectionType: "provenance",
    patterns: [
      "fetch\\(.*health", "axios\\.post\\(.*phi",
      "got\\(.*medical", "fetch\\(.*patient",
      "webhook\\(.*health", "webhook\\(.*phi",
      "sendEmail\\(.*health", "sendEmail\\(.*phi",
      "sendMail\\(.*medical", "sendMail\\(.*patient",
      "res\\.send\\(.*health", "res\\.json\\(.*phi",
    ],
    requiredControls: ["tls_encryption", "phi_safe_logging", "encrypted_webhooks", "secure_email_protocol"],
    fixAdvice: "Ensure all ePHI transmission uses TLS 1.2+. Implement integrity controls (message authentication codes or digital signatures). Never log ePHI in plaintext. Use encrypted webhook delivery. Use secure email protocols (SMTP over TLS, S/MIME encryption). Mask ePHI in API responses or logs where possible.",
    penaltyMaxEur: 50000,
  },
  {
    id: "HIPAA-011",
    framework: "hipaa",
    clause: "164.314(a)(1)",
    title: "Business associate contracts — no BAA for third-party processors",
    description: "HIPAA 164.314(a)(1) requires covered entities to obtain satisfactory assurances (Business Associate Agreement) that business associates will appropriately safeguard ePHI. Using third-party services that process ePHI without a signed BAA is a violation.",
    severity: "high",
    dataClassification: ["phi", "personal"],
    detectionType: "missing_implementation",
    patterns: [
      "baa", "BAA", "BusinessAssociate",
      "business.*associate.*agreement",
      "dpa", "data.*processing.*agreement",
      "hipaa.*compliant", "hipaaCompliant",
    ],
    requiredControls: ["baa_in_place", "business_associate_inventory", "vendor_risk_assessment", "contract_review"],
    fixAdvice: "Identify all business associates that process ePHI (cloud providers, analytics, email, billing, etc.). Execute HIPAA-compliant Business Associate Agreements with each. The BAA must require: appropriate safeguards, breach notification, agent compliance, and BAA termination if terms violated. Review annually. Maintain an inventory.",
    penaltyMaxEur: 50000,
  },

  // ══════════════════════════════════════════════════════════════════
  // WCAG 2.2 — W3C Web Content Accessibility Guidelines
  // ══════════════════════════════════════════════════════════════════
  {
    id: "WCAG-001",
    framework: "wcag",
    clause: "1.1.1",
    title: "Non-text content — missing alt attributes on images",
    description: "WCAG 2.2 Success Criterion 1.1.1 (Level A) requires text alternatives for all non-text content. Exceptions: controls (needs name), time-based media, tests, sensory, CAPTCHA, and decoration. Images without alt attributes are inaccessible to screen readers.",
    severity: "high",
    dataClassification: ["personal"],
    detectionType: "pattern",
    patterns: [
      "<img[^>]*src=[^>]*>", "<Image[^>]*src=[^>]*/>",
    ],
    excludePatterns: ["alt=", "alt\\s*=", 'alt=""', "alt=\\'\\'", "aria-label", "aria-hidden", "role=\"presentation\""],
    requiredControls: ["alt_attributes", "aria_labels", "semantic_html", "decorative_image_handling"],
    fixAdvice: "Add descriptive alt attributes to all meaningful images: `<img src=\"...\" alt=\"Description of image\">`. For decorative images, use `alt=\"\"` or `role=\"presentation\"`. For complex images (charts, diagrams), provide long descriptions via `aria-describedby` or adjacent text. Test with a screen reader.",
    penaltyMaxEur: 0,
  },
  {
    id: "WCAG-002",
    framework: "wcag",
    clause: "1.4.3",
    title: "Contrast (Minimum) — insufficient color contrast",
    description: "WCAG 2.2 Success Criterion 1.4.3 (Level AA) requires a contrast ratio of at least 4.5:1 for normal text and 3:1 for large text (18pt+ or 14pt+ bold). Hardcoded color values that may violate contrast ratios must be reviewed.",
    severity: "medium",
    dataClassification: ["personal"],
    detectionType: "pattern",
    patterns: [
      "color:\\s*#[0-9a-fA-F]{3}", "color:\\s*#[0-9a-fA-F]{6}",
      "backgroundColor:\\s*#[0-9a-fA-F]{3,6}",
      "background:\\s*#[0-9a-fA-F]{3,6}",
      "tailwind.*text-", "class:.*text-",
    ],
    requiredControls: ["color_contrast_checking", "accessible_color_palette", "contrast_testing_tools"],
    fixAdvice: "Use a color palette that passes WCAG AA contrast ratios (4.5:1 for normal text, 3:1 for large text). Tools: WebAIM Contrast Checker, axe DevTools, Lighthouse. Define CSS custom properties for accessible colors. Never use light-gray (#999 or lighter) for body text. Test with a color contrast analyzer.",
    penaltyMaxEur: 0,
  },
  {
    id: "WCAG-003",
    framework: "wcag",
    clause: "2.1.1",
    title: "Keyboard — interactive elements not keyboard accessible",
    description: "WCAG 2.2 Success Criterion 2.1.1 (Level A) requires all functionality to be operable through a keyboard interface without requiring specific timings. Click handlers on non-focusable elements (div, span) without keyboard event handlers violate this requirement.",
    severity: "high",
    dataClassification: ["personal"],
    detectionType: "pattern",
    patterns: [
      "onClick=\\{", "onClick=\\(",
      "@click=", "(click)=\"",
      "click={.*=>", "click={.*function",
    ],
    contextPatterns: ["<div", "<span", "<li", '<a[^>]*href="#'],
    requiredControls: ["keyboard_handlers", "focus_management", "tab_index", "role_attributes"],
    fixAdvice: "Add keyboard event handlers alongside click handlers: `onKeyDown={handleKeyDown}`. Use semantic HTML elements (`<button>`, `<a>`, `<input>`) instead of `<div>` for interactive elements. For non-semantic elements, add `tabIndex={0}` and `role='button'`. Ensure all functionality is accessible via Tab, Enter, and Space keys.",
    penaltyMaxEur: 0,
  },
  {
    id: "WCAG-004",
    framework: "wcag",
    clause: "2.1.2",
    title: "No keyboard trap — keyboard focus trapped in component",
    description: "WCAG 2.2 Success Criterion 2.1.2 (Level A) requires that keyboard focus is never trapped in a component. Users must be able to move focus away using only the keyboard. Custom modals, menus, and dialogs that trap focus without escape mechanisms violate this.",
    severity: "high",
    dataClassification: ["personal"],
    detectionType: "pattern",
    patterns: [
      "function Modal", "function Dialog",
      "const Modal", "const Dialog",
      "function Lightbox", "function Drawer",
    ],
    excludePatterns: ["focus.*trap", "focusTrap", "Escape.*close", "onKeyDown.*Escape", "handleEscape"],
    requiredControls: ["keyboard_trap_prevention", "escape_handler", "focus_trap_management", "modal_accessible"],
    fixAdvice: "Implement proper keyboard focus management for modals, dialogs, and drawers: trap focus within the component while open, but allow exiting via Escape key. Close the component on Escape. When closed, return focus to the triggering element. Use `aria-modal=\"true\"` and ensure the focus order is logical.",
    penaltyMaxEur: 0,
  },
  {
    id: "WCAG-005",
    framework: "wcag",
    clause: "2.4.1",
    title: "Bypass blocks — missing skip navigation link",
    description: "WCAG 2.2 Success Criterion 2.4.1 (Level A) requires a mechanism to bypass blocks of content repeated across pages. Applications without a skip-to-content link at the top of the page force keyboard users to tab through all navigation to reach main content.",
    severity: "medium",
    dataClassification: ["personal"],
    detectionType: "pattern",
    patterns: [
      "skip.*content", "skip.*nav", "skip.*main",
      "skip-to-content", "skipToContent",
      "skipLink", "skip_link",
      "href=\"#main\"", "href=\"#content\"",
    ],
    requiredControls: ["skip_navigation_link", "semantic_landmarks", "heading_hierarchy"],
    fixAdvice: "Add a skip-to-content link as the first focusable element: `<a href=\"#main-content\" class=\"skip-link\">Skip to main content</a>`. Style it to be visible on focus (not hidden). Ensure `<main id=\"main-content\">` is present. Use semantic HTML5 landmarks: `<nav>`, `<main>`, `<aside>`.",
    penaltyMaxEur: 0,
  },
  {
    id: "WCAG-006",
    framework: "wcag",
    clause: "2.4.3",
    title: "Focus order — focusable elements not in meaningful sequence",
    description: "WCAG 2.2 Success Criterion 2.4.3 (Level A) requires focusable components to receive focus in an order that preserves meaning and operability. Tab order that does not follow the visual layout or logical interaction flow violates this criterion.",
    severity: "medium",
    dataClassification: ["personal"],
    detectionType: "pattern",
    patterns: [
      "tabIndex=\\{[0-9]", "tabIndex=\\{-[0-9]",
      "tabindex=\"[0-9]", "tabindex=\"-",
      "tabIndex=\\{0}", "tabIndex=\\{-1}",
    ],
    requiredControls: ["logical_tab_order", "tab_index_management", "dom_order_match_visual"],
    fixAdvice: "Ensure the DOM order matches the visual reading order. Avoid using positive tabIndex values (use 0 or -1 only). Use semantic HTML elements which have built-in keyboard support. Test tab order by navigating with the Tab key. The focus order should follow the logical interaction flow left-to-right, top-to-bottom.",
    penaltyMaxEur: 0,
  },
  {
    id: "WCAG-007",
    framework: "wcag",
    clause: "2.4.7",
    title: "Focus visible — no visible keyboard focus indicator",
    description: "WCAG 2.2 Success Criterion 2.4.7 (Level AA) requires a visible keyboard focus indicator. Removing or disabling the default `:focus` outline without providing an alternative visible indicator is a violation. Users must be able to see which element has keyboard focus at all times.",
    severity: "high",
    dataClassification: ["personal"],
    detectionType: "pattern",
    patterns: [
      "outline:\\s*none", "outline:\\s*0",
      "outline: none", "outline: 0",
      "outline=\"0\"", "outline='0'",
    ],
    excludePatterns: ["focus-visible", "focus.*outline", ":focus-visible", "focus-ring"],
    requiredControls: ["visible_focus_indicator", "focus_ring", "focus_style", "high_contrast_focus"],
    fixAdvice: "Never remove the default focus outline without providing an alternative. Use `:focus-visible` to show a focus ring only when navigating by keyboard: `:focus-visible { outline: 2px solid #4A90D9; outline-offset: 2px; }`. Ensure the focus indicator has at least 3:1 contrast ratio against adjacent colors.",
    penaltyMaxEur: 0,
  },
  {
    id: "WCAG-008",
    framework: "wcag",
    clause: "2.5.8",
    title: "Target size (Minimum) — pointer targets too small",
    description: "WCAG 2.2 Success Criterion 2.5.8 (Level AA, NEW in WCAG 2.2) requires pointer targets to be at least 24x24 CSS pixels. Smaller clickable elements (icons, buttons, links) fail this criterion, making them difficult to activate for users with motor impairments or on touch devices.",
    severity: "medium",
    dataClassification: ["personal"],
    detectionType: "pattern",
    patterns: [
      "width:\\s*[0-9]{1,2}px[^;]*height:\\s*[0-9]{1,2}px",
      "height:\\s*[0-9]{1,2}px[^;]*width:\\s*[0-9]{1,2}px",
      "w-[0-9]", "h-[0-9]",
      "w-1", "w-2", "w-3", "h-1", "h-2", "h-3",
    ],
    requiredControls: ["minimum_target_size", "touch_target_sizing", "hit_area_expansion"],
    fixAdvice: "Ensure all interactive targets are at least 24x24 CSS pixels. For small icons or buttons, use `padding` or `::before`/`::after` pseudo-elements to expand the hit area to 24x24px. Exception: inline links within text blocks, and controls where the target is controlled by the user agent. Test with mobile viewports.",
    penaltyMaxEur: 0,
  },
  {
    id: "WCAG-009",
    framework: "wcag",
    clause: "3.2.6",
    title: "Consistent help — help mechanisms in inconsistent locations",
    description: "WCAG 2.2 Success Criterion 3.2.6 (Level A, NEW in WCAG 2.2) requires help mechanisms (contact details, chat, FAQ, help pages) to appear in the same relative order across pages when repeated. Moving help links between pages disorients users.",
    severity: "low",
    dataClassification: ["personal"],
    detectionType: "pattern",
    patterns: [
      "help", "faq", "support", "contact.*us",
      "/help", "/faq", "/support",
      "liveChat", "chatWidget", "helpCenter",
    ],
    requiredControls: ["consistent_help_location", "help_mechanism_standardization", "predictable_navigation"],
    fixAdvice: "Place help mechanisms (FAQ link, contact us, chat widget, help center link) in a consistent relative order across all pages. For example, always place 'Help' after 'About' and before 'Contact' in the navigation. Avoid moving or reordering help links between pages.",
    penaltyMaxEur: 0,
  },
  {
    id: "WCAG-010",
    framework: "wcag",
    clause: "3.3.2",
    title: "Labels or instructions — form inputs without labels",
    description: "WCAG 2.2 Success Criterion 3.3.2 (Level A) requires labels or instructions when content requires user input. Form fields without `<label>` elements, `aria-label`, or `aria-labelledby` attributes are inaccessible to screen reader users.",
    severity: "high",
    dataClassification: ["personal"],
    detectionType: "pattern",
    patterns: [
      "<input[^>]*>", "<select[^>]*>", "<textarea[^>]*>",
      "<Input[^>]*/>", "<Select[^>]*/>",
    ],
    excludePatterns: [
      "type=\"hidden\"", "aria-label=", "aria-labelledby=",
      "<label", "placeholder=", "type=\"submit\"",
      "type=\"button\"", "type=\"reset\"",
    ],
    requiredControls: ["form_labels", "aria_descriptions", "error_messages", "semantic_forms"],
    fixAdvice: "Wrap form inputs in `<label>` elements: `<label>Email: <input type=\"email\" /></label>`. Alternatively use `aria-label`: `<input aria-label=\"Email address\" />`. For grouping, use `<fieldset>` and `<legend>`. Provide clear error messages linked with `aria-describedby`. Test all forms with a screen reader.",
    penaltyMaxEur: 0,
  },
  {
    id: "WCAG-011",
    framework: "wcag",
    clause: "3.3.7",
    title: "Redundant entry — asking for previously entered information",
    description: "WCAG 2.2 Success Criterion 3.3.7 (Level A, NEW in WCAG 2.2) requires that information previously entered by or provided to the user is not required to be re-entered in the same session. Multi-step forms and wizards that ask for the same data twice violate this criterion.",
    severity: "medium",
    dataClassification: ["personal"],
    detectionType: "pattern",
    patterns: [
      "confirmEmail", "confirm.*email",
      "re-enter", "reenter", "re_type",
      "confirmPassword", "confirm.*password",
    ],
    requiredControls: ["session_data_persistence", "multi_step_form_state", "auto_fill_reuse"],
    fixAdvice: "Cache user-provided data within a session and auto-fill it when needed in subsequent steps. For multi-step processes, pass data between steps without requiring re-entry. Exceptions: security-critical fields (passwords), or when ensuring accuracy of medical/financial information where re-entry serves a verification purpose.",
    penaltyMaxEur: 0,
  },
  {
    id: "WCAG-012",
    framework: "wcag",
    clause: "3.3.8",
    title: "Accessible Authentication (Minimum) — cognitive function tests for authentication",
    description: "WCAG 2.2 Success Criterion 3.3.8 (Level AA, NEW in WCAG 2.2) requires that authentication does not rely on a cognitive function test (e.g., remembering a password, solving a puzzle, or recalling a previous entry). CAPTCHAs requiring pattern recognition, transcription, or memory tasks violate this criterion. Exceptions: object recognition, personal content, and multi-factor authentication.",
    severity: "high",
    dataClassification: ["credentials", "personal"],
    detectionType: "pattern",
    patterns: [
      "captcha", "CAPTCHA", "recaptcha", "reCaptcha",
      "g-recaptcha", "hcaptcha", "hCaptcha",
      "turnstile", "cloudflare.*challenge",
      "puzzle.*solved", "image.*select",
      "audio.*captcha",
    ],
    requiredControls: ["alternative_authentication", "cognitive_function_bypass", "mfa_alternative", "password_manager_support"],
    fixAdvice: "Replace cognitive-function-dependent authentication (CAPTCHAs, puzzles, memory tasks) with: password manager support (autofill), WebAuthn/passkeys, OAuth single sign-on, magic links, QR code login, or multi-factor authentication (TOTP, hardware keys). If a CAPTCHA is necessary, offer an audio or alternative mechanism per WCAG exception.",
    penaltyMaxEur: 0,
  },
  {
    id: "WCAG-013",
    framework: "wcag",
    clause: "4.1.2",
    title: "Name, role, value — custom components missing ARIA attributes",
    description: "WCAG 2.2 Success Criterion 4.1.2 (Level A) requires all interactive UI components to have programmatic name, role, value, states, and properties. Custom components (modals, dropdowns, tabs, accordions, menus) without appropriate ARIA attributes are inaccessible.",
    severity: "high",
    dataClassification: ["personal"],
    detectionType: "pattern",
    patterns: [
      "function Modal", "function Dropdown", "function Tooltip",
      "function Popover", "function Tab", "function Accordion",
      "function Dialog", "function Menu", "function Combobox",
      "const Modal", "const Dropdown", "const Tooltip",
      "const Popover", "const Tab", "const Accordion",
    ],
    requiredControls: ["aria_roles", "aria_states", "focus_trapping", "keyboard_navigation", "accessible_naming"],
    fixAdvice: "Add ARIA roles to custom components: `role=\"dialog\"` for modals, `role=\"tablist\"`/`role=\"tab\"`/`role=\"tabpanel\"` for tabs, `role=\"menu\"`/`role=\"menuitem\"` for menus, `role=\"combobox\"` for autocomplete. Add `aria-expanded`, `aria-selected`, `aria-hidden` for states. Use `aria-label` or `aria-labelledby` for naming. Implement keyboard navigation.",
    penaltyMaxEur: 0,
  },

  // ══════════════════════════════════════════════════════════════════
  // CCPA/CPRA — California Consumer Privacy Act (2018, amended 2020)
  // ══════════════════════════════════════════════════════════════════
  {
    id: "CCPA-001",
    framework: "ccpa",
    clause: "1798.100(a)",
    title: "Right to know at collection — no notice at data collection point",
    description: "CCPA 1798.100(a) requires businesses to inform consumers of the categories of personal information to be collected and the purposes for which it will be used at or before the point of collection. Forms and input fields that collect data without a privacy notice violate this right.",
    severity: "high",
    dataClassification: ["pii", "personal"],
    detectionType: "missing_implementation",
    patterns: [
      "privacy.*notice", "privacyNotice",
      "at.*collection.*notice", "collection.*notice",
      "data.*collection.*notice", "collect.*notice",
      "privacy.*at.*point", "point.*of.*collection",
    ],
    requiredControls: ["collection_notice", "purpose_disclosure", "privacy_policy_update", "data_category_disclosure"],
    fixAdvice: "Add a notice at or before each point of data collection stating: categories of personal info being collected, and purposes for which it will be used. This can be a link to a full privacy policy: `By submitting this form, you agree to our <a href=\"/privacy\">Privacy Policy</a>`. Review and update the privacy policy with CCPA-required disclosures.",
    penaltyMaxEur: 7500,
  },
  {
    id: "CCPA-002",
    framework: "ccpa",
    clause: "1798.100(e)",
    title: "Reasonable security procedures — no data security measures",
    description: "CCPA 1798.100(e) requires businesses to implement and maintain reasonable security procedures and practices appropriate to the nature of the personal information. Failure to implement basic security controls (encryption, access controls, monitoring) creates liability under CCPA's private right of action for data breaches.",
    severity: "critical",
    dataClassification: ["pii", "personal", "credentials"],
    detectionType: "missing_implementation",
    patterns: [
      "encrypt", "encryption",
      "access.*control", "security.*measure",
      "data.*protection", "safeguard",
      "security.*procedure", "infoSec",
    ],
    requiredControls: ["reasonable_security", "encryption_at_rest", "encryption_in_transit", "access_controls", "security_monitoring"],
    fixAdvice: "Implement reasonable security procedures including: encryption of personal information at rest (AES-256) and in transit (TLS 1.2+), access controls with least privilege, security monitoring (SIEM), incident response plan, vulnerability management, and regular security training. Document all security practices.",
    penaltyMaxEur: 7500,
  },
  {
    id: "CCPA-003",
    framework: "ccpa",
    clause: "1798.105(a)",
    title: "Right to delete — no consumer deletion mechanism",
    description: "CCPA 1798.105(a) grants consumers the right to request deletion of personal information collected by the business. The business must delete the information and instruct service providers, contractors, and third parties to delete it as well. Exceptions include completing transactions, security, legal compliance, and internal uses consistent with context.",
    severity: "high",
    dataClassification: ["pii", "personal", "credentials"],
    detectionType: "missing_implementation",
    patterns: [
      "delete.*request", "deletionRequest",
      "right.*delete", "right-to-delete",
      "data.*deletion", "account.*deletion",
      "delete.*my.*data", "remove.*my.*data",
    ],
    requiredControls: ["deletion_request_endpoint", "data_deletion_procedure", "service_provider_deletion", "deletion_exceptions_handling"],
    fixAdvice: "Implement a consumer deletion request mechanism (web form, email, toll-free number). Process verifiable deletion requests within 45 days (extendable by 45 days with notice). Delete the consumer's personal information and notify all service providers/contractors/third parties to do the same. Handle exceptions per 1798.105(d).",
    penaltyMaxEur: 7500,
  },
  {
    id: "CCPA-004",
    framework: "ccpa",
    clause: "1798.110(a)",
    title: "Right to know/access — no mechanism for data access request",
    description: "CCPA 1798.110(a) gives consumers the right to request disclosure of: categories of personal info collected, sources, business/commercial purpose for collection, categories of third parties shared with, and specific pieces of personal info. Businesses must respond to verifiable requests within 45 days.",
    severity: "high",
    dataClassification: ["pii", "personal"],
    detectionType: "missing_implementation",
    patterns: [
      "access.*request", "dataAccessRequest",
      "right.*know", "right-to-know",
      "personal.*info.*request", "data.*subject.*request",
      "dsr", "DSR", "dataSubjectRequest",
    ],
    requiredControls: ["access_request_endpoint", "verification_procedure", "response_within_45_days", "category_disclosure"],
    fixAdvice: "Implement an access request mechanism allowing consumers to request: (1) categories of PI collected, (2) sources, (3) business/commercial purpose, (4) third-party categories, (5) specific PI pieces. Verify the consumer's identity before disclosing. Respond within 45 days (extend by 45 with notice). Provide information free of charge per 12-month period.",
    penaltyMaxEur: 7500,
  },
  {
    id: "CCPA-005",
    framework: "ccpa",
    clause: "1798.120(a)",
    title: "Right to opt-out of sale/sharing — no opt-out mechanism",
    description: "CCPA 1798.120(a) grants consumers the right to opt out of the sale or sharing of their personal information. Businesses that sell or share personal information must provide a clear and conspicuous link titled 'Do Not Sell or Share My Personal Information' and honor opt-out requests.",
    severity: "high",
    dataClassification: ["pii", "personal"],
    detectionType: "missing_implementation",
    patterns: [
      "do-not-sell", "doNotSell", "dntSignal",
      "ccpa-opt-out", "ccpaOptOut",
      "your-privacy-choices", "privacy-choices",
      "data-sale-opt-out", "sale-opt-out",
      "opt.*out.*sale", "optOutOfSale",
    ],
    requiredControls: ["opt_out_mechanism", "dnspi_link", "global_privacy_control", "opt_out_records"],
    fixAdvice: "Add a 'Do Not Sell or Share My Personal Information' link on the website homepage and all collection points. Implement an opt-out mechanism that records user preference. Support the Global Privacy Control (GPC) signal. Honor opt-out requests within 15 business days. Do not request re-consent for 12 months after opt-out.",
    penaltyMaxEur: 7500,
  },
  {
    id: "CCPA-006",
    framework: "ccpa",
    clause: "1798.125(a)",
    title: "Right to non-discrimination — penalizing consumers for exercising rights",
    description: "CCPA 1798.125(a) prohibits businesses from denying goods/services, charging different prices, or providing different quality of service to consumers who exercise CCPA rights. The exception: financial incentives reasonably related to the value of consumer data are permitted with prior opt-in consent.",
    severity: "medium",
    dataClassification: ["pii", "personal"],
    detectionType: "pattern",
    patterns: [
      "premium.*consent", "premium.*privacy",
      "pay.*for.*privacy", "privacy.*fee",
      "discount.*data.*share", "reward.*data",
      "loyalty.*program.*data",
    ],
    requiredControls: ["non_discrimination_policy", "financial_incentive_compliance", "loyalty_program_review"],
    fixAdvice: "Review all pricing, service tiers, and loyalty programs for discrimination against CCPA rights-exercising consumers. If offering financial incentives for data collection, ensure: (1) the incentive is reasonably related to data value, (2) consumers opt in with prior informed consent, (3) the incentive terms are clearly disclosed, and (4) consumers can revoke consent.",
    penaltyMaxEur: 7500,
  },
  {
    id: "CCPA-007",
    framework: "ccpa",
    clause: "1798.130(a)(1)(A)",
    title: "Methods for submitting requests — less than two methods offered",
    description: "CCPA 1798.130(a)(1)(A) requires businesses to provide two or more methods for consumers to submit data requests (including at minimum a toll-free number). Online-only businesses may provide an email address as one method. A single contact method is insufficient.",
    severity: "medium",
    dataClassification: ["pii", "personal"],
    detectionType: "missing_implementation",
    patterns: [
      "contact.*us", "contactUs",
      "privacy.*request", "data.*request",
      "submit.*request", "request.*form",
      "toll.*free", "tollFree",
    ],
    requiredControls: ["multiple_submission_methods", "toll_free_number", "online_form", "email_method"],
    fixAdvice: "Provide at least two methods for consumers to submit CCPA requests: (1) a toll-free telephone number, and (2) either a web form or email address. Online-only businesses can use email as one method. Ensure all methods are accessible and clearly described in the privacy policy. Process all requests through the same workflow regardless of submission method.",
    penaltyMaxEur: 7500,
  },
  {
    id: "CCPA-008",
    framework: "ccpa",
    clause: "1798.135(a)(1)",
    title: "Do Not Sell or Share link — missing conspicuous link",
    description: "CCPA 1798.135(a)(1) requires businesses that sell or share personal information to provide a conspicuous link on the homepage and at any collection point titled 'Do Not Sell or Share My Personal Information'. The link must be in a standard format and accessible without logging in. Failure to provide this link is a common enforcement action target.",
    severity: "high",
    dataClassification: ["pii", "personal"],
    detectionType: "pattern",
    patterns: [
      "do-not-sell", "doNotSell", "DoNotSell",
      "ccpa-opt-out", "ccpaOptOut",
      "your-privacy-choices", "privacy-choices",
      "data-sale-opt-out", "sale-opt-out",
      "dnspi", "DNSPI",
    ],
    requiredControls: ["dnspi_link_homepage", "conspicuous_placement", "accessible_without_login", "standard_naming"],
    fixAdvice: "Add a conspicuous 'Do Not Sell or Share My Personal Information' link on the website homepage header/footer and on any page where personal information is collected. The link must be accessible to users without logging in. Use the standard naming convention required by CCPA regulations. Do not require users to create or log into an account to opt out.",
    penaltyMaxEur: 7500,
  },
];

export const COMPLIANCE_CATEGORIES: Record<string, { name: string; description: string }> = {
  gdpr: { name: "GDPR", description: "General Data Protection Regulation (European Union)" },
  pci_dss: { name: "PCI-DSS", description: "Payment Card Industry Data Security Standard" },
  soc2: { name: "SOC 2", description: "Service Organization Control 2 (AICPA)" },
  hipaa: { name: "HIPAA", description: "Health Insurance Portability and Accountability Act (US)" },
  wcag: { name: "WCAG", description: "Web Content Accessibility Guidelines (W3C)" },
  ccpa: { name: "CCPA", description: "California Consumer Privacy Act" },
};

export const FRAMEWORK_PENALTIES: Record<string, { maxFineEur: number; description: string }> = {
  gdpr: { maxFineEur: 20000000, description: "Up to €20M or 4% of annual global turnover (whichever is higher)" },
  pci_dss: { maxFineEur: 0, description: "$5,000-$100,000/month per card brand (Visa, Mastercard, AmEx, Discover)" },
  soc2: { maxFineEur: 0, description: "Loss of certification, contract termination, legal liability — no direct regulatory fines" },
  hipaa: { maxFineEur: 50000, description: "$100-$50,000 per violation, up to $1.5M per provision per calendar year" },
  wcag: { maxFineEur: 0, description: "ADA lawsuits $10,000-$100,000+ per lawsuit; DOJ settlements typically $50K+" },
  ccpa: { maxFineEur: 7500, description: "$2,500 per unintentional violation, $7,500 per intentional violation" },
};
