import { type CodeContext, getAnyClient, smartModel, extractJson } from "./agents.js";
import { type CSG } from "./csg-builder.js";
import { logger } from "./logger.js";

export interface VerifiedFinding {
  id: string;
  category: string;
  severity: "critical" | "high" | "medium" | "low";
  title: string;
  description: string;
  filePath: string;
  lineNumber?: number;
  confidence: number; // The final Dempster-Shafer fused confidence
  aiVerified: boolean;
  aiContext?: string;
  funnelStage?: string;
}

/**
 * Dempster-Shafer Evidence Fusion
 * Mathematically combines belief masses from independent analytical engines.
 * 
 * m1: Belief mass from the deterministic graph engine (0.0 to 1.0)
 * m2: Belief mass from the LLM contextual verifier (0.0 to 1.0)
 * 
 * Both engines provide evidence for proposition A (True Positive).
 * m1(A) = m1, m1(Theta) = 1 - m1
 * m2(A) = m2, m2(Theta) = 1 - m2
 */
function fuseDempsterShafer(m1: number, m2: number): number {
  // Calculate orthogonal sum (Dempster's Rule of Combination)
  // m12(A) = (m1(A)*m2(A) + m1(A)*m2(Theta) + m1(Theta)*m2(A)) / (1 - K)
  // K is the conflict, which is 0 when combining evidence for the same proposition.
  
  const m1_A = m1 / 100;
  const m1_Theta = 1 - m1_A;
  
  const m2_A = m2 / 100;
  const m2_Theta = 1 - m2_A;

  // The combined belief mass for True Positive
  const combined_A = (m1_A * m2_A) + (m1_A * m2_Theta) + (m1_Theta * m2_A);
  
  return Math.min(Math.round(combined_A * 100), 100);
}

/**
 * Multi-Engine Consensus Layer (AI Verifier)
 * 1. Takes all raw findings from the 10 deep tech pillars.
 * 2. Groups them by file.
 * 3. Serializes the deterministic structures (CSG paths, SCET costs) and sends them to the LLM.
 * 4. Fuses confidence scores.
 */
export async function runAIVerifier(csg: CSG, keyFiles: Array<{path: string; content: string}>, rawFindings: Array<any>): Promise<VerifiedFinding[]> {
  logger.info({ findingsCount: rawFindings.length }, "Running Multi-Engine Consensus AI Verifier...");

  if (rawFindings.length === 0) return [];

  // Batch process findings to save API calls
  const BATCH_SIZE = 10;
  const verified: VerifiedFinding[] = [];
  const client = getAnyClient();
  const model = smartModel();

  for (let i = 0; i < rawFindings.length; i += BATCH_SIZE) {
    const batch = rawFindings.slice(i, i + BATCH_SIZE);
    
    // Build context
    const batchContext = batch.map(finding => {
      const file = keyFiles.find(f => f.path === finding.filePath);
      return `
Finding ID: ${finding.id || 'N/A'}
Category: ${finding.category}
Severity: ${finding.severity}
Title: ${finding.title}
Deterministic Description: ${finding.description}
Engine Confidence: ${finding.confidence || 80}%
File: ${finding.filePath}
Code Snippet:
\`\`\`
${file ? file.content.substring(0, 1500) : "Source not available."}
\`\`\`
`;
    }).join("\n---\n");

    const prompt = `You are the Multi-Engine Consensus AI Verifier for a deep-tech code analysis platform.
You are receiving a batch of deterministic findings generated by advanced graph-theoretic and probabilistic engines (e.g., RT-IFC, CSG traversal, Symbolic Cost Models).
Your job is to cross-reference the deterministic findings against the raw source code snippet provided, match them with traditional deep tech patterns, and act as a rigorous mathematical filter.

Look out for:
- False positives: e.g., the engine flagged an SQL injection, but the code actually passes it to Prisma's tagged template which is formally safe.
- False positives: e.g., the engine flagged a missing try/catch, but there is a global ErrorBoundary handling it at the AST root.
- Accurate findings: e.g., the engine flagged an implicit control flow leak, and the code confirms the conditional branch depends on tainted data.
We have executed multiple deterministic engines including Abstract Interpretation, Dempster-Shafer Data Fusion, Z3 SMT Constraints, Shannon Entropy analysis, and Linear Temporal Logic (LTL) checks.

You must review these findings and provide a formal proof of verification. If you detect a false positive caused by an over-approximation or a constraint solver bounds error, flag it.

Each object MUST have the following schema:
[
  {
    "id": "The Finding ID exactly as provided",
    "isFalsePositive": boolean,
    "aiConfidence": number (0-100, the belief mass you assign to this assessment based on the evidence),
    "aiContext": "A detailed formal proof of your verification matching the deep tech pattern (e.g., 'Formal Proof: The taint from req.body mathematically terminates at the Zod boundary on line 42, validating the engine's inference. The control-dependence edge is correctly flagged.')"
  }
]

Batch to verify:
${batchContext}
`;

    try {
      const completion = await client.chat.completions.create({
        messages: [{ role: "user", content: prompt }],
        model,
        temperature: 0.1,
      });

      const responseText = completion.choices[0]?.message?.content || "[]";
      const jsonStr = extractJson(responseText);
      const aiResults = JSON.parse(jsonStr);

      for (const finding of batch) {
        const aiAssessment = Array.isArray(aiResults) ? aiResults.find((a: any) => a.id === finding.id) : null;
        
        if (aiAssessment) {
          if (aiAssessment.isFalsePositive && aiAssessment.aiConfidence > 70) {
            // Drop it, it's a high-confidence false positive
            continue;
          }

          const finalConfidence = fuseDempsterShafer(finding.confidence || 80, aiAssessment.aiConfidence || 80);
          
          verified.push({
            ...finding,
            aiVerified: true,
            aiContext: aiAssessment.aiContext || "Verified by AI consensus layer.",
            confidence: finalConfidence,
          });
        } else {
          // Fallback if AI missed it
          verified.push({
            ...finding,
            aiVerified: false,
            confidence: finding.confidence || 80,
          });
        }
      }
    } catch (err) {
      logger.error({ err }, "AI Verifier batch failed, falling back to deterministic results.");
      // Fallback
      for (const finding of batch) {
        verified.push({ ...finding, aiVerified: false, confidence: finding.confidence || 80 });
      }
    }
  }

  logger.info({ verifiedCount: verified.length, dropped: rawFindings.length - verified.length }, "Multi-Engine Consensus Complete.");
  return verified;
}
